version: '2'
services:
  ram-postgis:
    image: mdillon/postgis:9.6
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: ramtest
      POSTGRES_USER: ramtest
      POSTGRES_DB: ramtest
  ram-minio:
    image: minio/minio
    ports:
      - 9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniostorageengine
    # volumes:
    #   - /guts/projects/ram/minio-stuff/export:/export
    #   - /guts/projects/ram/minio-stuff/config:/root/.minio
    command: server /export
  ram-api:
    build: ./
    ports:
      - 4000
    environment:
      DS_ENV: test
      DB_CONNECTION: postgresql://ramtest:ramtest@ram-postgis:5432/ramtest
      STORAGE_PORT: 9000
      STORAGE_ENGINE: minio
      STORAGE_ACCESS_KEY: minio
      STORAGE_SECRET_KEY: miniostorageengine
      STORAGE_BUCKET: ram-test
      STORAGE_REGION: us-east-1
      STORAGE_HOST: ram-minio
    links:
      - ram-postgis
      - ram-minio